In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
# If we want to save the array we use np.save()
np.save('myarray', arr)

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# This is how we load our saved array.
# We must use the name of the array followed by the extension
# .npy
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [8]:
# We can save multiple arrays

arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr2 = arr

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# To save multiple arrays we use np.savez() a zip array.
# We must save with a .npz extension
np.savez('ziparray.npz', x=arr1,y=arr2)

In [12]:
archive_arr = np.load('ziparray.npz')

In [13]:
archive_arr['x']

array([0, 1, 2, 3, 4])

In [14]:
archive_arr['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# We can also save and load text files

arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.savetxt('mytextarray.txt', arr, delimiter =',')

In [19]:
arr = np.loadtxt('mytextarray.txt', delimiter = ',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])