In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# We can take the square root of every element in our array
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
# We can also take the exponential
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([ 0.10920969, -0.23270388, -1.86702364,  0.17852039,  1.42351339,
       -0.40841629, -1.04047065,  1.83395475, -0.70104677, -0.17221124])

In [7]:
B = np.random.randn(10)
B

array([-0.44034586,  0.02908158,  0.13284845, -1.51930539,  0.03756458,
       -0.50215205,  1.80487763,  1.43947164, -1.10674035,  0.88965401])

In [8]:
# There are also binary functions 
# We can add arrays
np.add(A,B)

array([-0.33113617, -0.2036223 , -1.7341752 , -1.340785  ,  1.46107797,
       -0.91056834,  0.76440698,  3.27342639, -1.80778712,  0.71744277])

In [9]:
# Can find max in both arrays 
np.maximum(A,B)

array([ 0.10920969,  0.02908158,  0.13284845,  0.17852039,  1.42351339,
       -0.40841629,  1.80487763,  1.83395475, -0.70104677,  0.88965401])

In [10]:
# There are more functions and can be accessed
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True