In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# We can concatenate arrays along the rows stacking them
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# We can concatenate arraus along the columns 
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [10]:
# We will see how to do this in pandas
ser1 = Series([0,1,2], index = ['T','U','V'])

ser1

T    0
U    1
V    2
dtype: int64

In [11]:
ser2 = Series([3,4], index = ['X','Y'])
ser2

X    3
Y    4
dtype: int64

In [13]:
# concat with pandas will concatenat along the 0 axis 
# by default. 
pd.concat([ser1,ser2])

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [14]:
# Using another axis will return a DataFrame
pd.concat([ser1,ser2], axis =1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [15]:
# We can specify which specific axes to be used
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0

In [17]:
# We can add markers.keys to the concatenation
# here I add the name of the series.
pd.concat([ser1,ser2], keys=['ser1','ser2'])

ser1  T    0
      U    1
      V    2
ser2  X    3
      Y    4
dtype: int64

In [19]:
# Along axis one these keys become the headers of the
# dataframe
pd.concat([ser1,ser2], axis =1, keys=['ser1','ser2'])

ser1  ser2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [20]:
# The behavior is maintained with dataframes
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [21]:
dframe1

X         Y         Z
0 -0.412778  0.198792 -0.087929
1  0.339859 -0.318720 -0.874634
2  1.715785 -0.797904  0.426227
3 -0.880584  1.415213 -0.333155

In [22]:
dframe2

Y         Q         X
0 -0.391460 -1.701356 -0.787042
1  1.541500 -1.740383  0.485756
2 -1.470018 -0.783516  1.013629

In [23]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.412778  0.198792 -0.087929
1       NaN  0.339859 -0.318720 -0.874634
2       NaN  1.715785 -0.797904  0.426227
3       NaN -0.880584  1.415213 -0.333155
0 -1.701356 -0.787042 -0.391460       NaN
1 -1.740383  0.485756  1.541500       NaN
2 -0.783516  1.013629 -1.470018       NaN

In [24]:
# If we dont care about the index information. We can 
# create a complete DateFrame, using ignore_index

pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.412778  0.198792 -0.087929
1       NaN  0.339859 -0.318720 -0.874634
2       NaN  1.715785 -0.797904  0.426227
3       NaN -0.880584  1.415213 -0.333155
4 -1.701356 -0.787042 -0.391460       NaN
5 -1.740383  0.485756  1.541500       NaN
6 -0.783516  1.013629 -1.470018       NaN

In [ ]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'